### ISSUE TITLE
How to run this source code?

### ISSUE THREAD

**Issue by tphankr** [uncbiag/easyreg#11]
Please, help me understand. How to use this source code and run step by step in order to have results? thank you.
I set up the environment completely.
** Which file can I run before?
![image](https://user-images.githubusercontent.com/37217354/117554344-08a14f80-b025-11eb-9575-be75a4290ad3.png)

Thank you very much.

**Comment by marcniethammer** [comment]
There is documentation here: https://easyreg-unc-biag.readthedocs.io/en/latest/
